export const VALID_ROLES = ["user", "lawyer", "admin"];

export const FIELD_MAPPING: { [key: string]: string } = {
    BoMayHanhChinh: "Bộ máy hành chính",
    TaiChinhNhaNuoc: "Tài chính nhà nước",
    VanHoaXaHoi: "Văn hóa - Xã hội",
    TaiNguyenMoiTruong: "Tài nguyên - Môi trường",
    ThuongMai: "Thương mại",
    XayDungDoThi: "Xây dựng - Đô thị",
    BatDongSan: "Bất động sản",
    TheThaoYTe: "Thể thao - Y tế",
    ThuePhiLePhi: "Thuế - Phí - Lệ Phí",
    GiaoDuc: "Giáo dục",
    GiaoThongVanTai: "Giao thông - Vận tải",
    LaoDongTienLuong: "Lao động - Tiền lương",
    DoanhNghiep: "Doanh nghiệp",
    DauTu: "Đầu tư",
    CongNgheThongTin: "Công nghệ thông tin",
    XuatNhapKhau: "Xuất nhập khẩu",
    LinhVucKhac: "Lĩnh vực khác",
    TienTeNganHang: "Tiền tệ - Ngân hàng",
    QuyenDanSu: "Quyền dân sự",
    BaoHiem: "Bảo hiểm",
    DichVuPhapLy: "Dịch vụ pháp lý",
    ViPhamHanhChinh: "Vi phạm hành chính",
    ThuTucTotung: "Thủ tục Tố tụng",
    KeToanKiemToan: "Kế toán - Kiểm toán",
    TrachNhiemHinhSu: "Trách nhiệm hình sự",
    SoHuuTriTue: "Sở hữu trí tuệ",
    ChungKhoan: "Chứng khoán",
};

export const CATEGORY_MAPPING: { [key: string]: string } = {
    // BaoCao: "Báo cáo",
    // ChiThi: "Chỉ thị",
    // CongDien: "Công điện",
    // CongUoc: "Công ước",
    HienPhap: "Hiến pháp",
    // HiepDinh: "Hiệp định",
    // HuongDan: "Hướng dẫn",
    // KeHoach: "Kế hoạch",
    Luat: "Luật",
    Lenh: "Lệnh",
    NghiQuyet: "Nghị quyết",
    NghiDinh: "Nghị định",
    // NghiDinhThu: "Nghị định thư",
    PhapLenh: "Pháp lệnh",
    // QuyChe: "Quy chế",
    // QuyDinh: "Quy định",
    QuyetDinh: "Quyết định",
    // ThoaThuan: "Thoả thuận",
    // ThongBao: "Thông báo",
    // ThongTri: "Thông tri",
    ThongTu: "Thông tư",
    ThongTuLienTich: "Thông tư liên tịch",
    // VanBanWTO: "Văn bản WTO",
    // VanBanHopNhat: "Văn bản hợp nhất",
    // VanBanKhac: "Văn bản khác",
    // WTO_CamKetVN: "WTO_Cam kết VN",
    // WTO_VanBan: "WTO_Văn bản",
    // DieuLe: "Điều lệ",
    // DieuUoc: "Điều ước",
    // DieuUocQuocTe: "Điều ước quốc tế",
};

export const DEPARTMENT_MAPPING: { [key: string]: string } = {
    BoBuuChinhVienThong: "Bộ Bưu chính, Viễn thông",
    BoCongAn: "Bộ Công An",
    BoKeHoachVaDauTu: "Bộ Kế hoạch và Đầu tư",
    BoVanHoaThongTin: "Bộ Văn hoá-Thông tin",
    BoNgoaiGiao: "Bộ Ngoại giao",
    BoQuocPhong: "Bộ Quốc phòng",
    BoTaiNguyenVaMoiTruong: "Bộ Tài nguyên và Môi trường",
    BoNoiVu: "Bộ Nội vụ",
    BoTaiChinh: "Bộ Tài chính",
    BoChinhTri: "Bộ Chính trị",
    BoCongThuong: "Bộ Công thương",
    BoGiaoThongVanTai: "Bộ Giao thông vận tải",
    BoKhoaHocVaCongNghe: "Bộ Khoa học và Công nghệ",
    BoYTe: "Bộ Y tế",
    BoNongNghiepVaPhatTrienNongThon: "Bộ Nông nghiệp và Phát triển nông thôn",
    BoThuongMai: "Bộ Thương mại",
    BoTuPhap: "Bộ Tư pháp",
    BoGiaoDucVaDaoTao: "Bộ Giáo dục và Đào tạo",
    BoLaoDongThuongBinhVaXaHoi: "Bộ Lao động - Thương binh và Xã hội",
    BoLaoDong_ThuongBinhVaXaHoi: "Bộ Lao động – Thương binh và Xã hội",
    BoVanHoaTheThaoVaDuLich: "Bộ Văn hóa thể thao và du lịch",
    ToaAnNhaDanToiCao: "Tòa án nhân dân tối cao",
    VienKiemSatNhaDanToiCao: "Viện kiểm sát nhân dân tối cao",
    VienCongToTrungUong: "Viện công tố trung ương",
    ThanhTraChinhPhu: "Thanh tra Chính phủ",
    BoThongTinVaTruyenThong: "Bộ Thông tin và Truyền thông",
    KiemToanNhaNuoc: "Kiểm toán Nhà nước",
    BoThuySan: "Bộ Thuỷ sản",
    BoXayDung: "Bộ Xây dựng",
    TrungUongDoanThanhNienCongSanHoChiMinh:
        "Trung ương Đoàn thanh niên cộng sản Hồ Chí Minh",
    BoKhoaHocCongNghe: "Bộ Khoa học công nghệ",
    BoKeHoachDauTu: "Bộ Kế hoach Đầu tư",
    BoNongNghiepVaCongNghiepThucPham: "Bộ Nông nghiệp và Công nghiệp thực phẩm",
    BoNoiThuong: "Bộ Nội thương",
    BoVanHoaVaThongTin: "Bộ Văn hoá và Thông tin",
    BoTaiNguyenMoiTruong: "Bộ Tài nguyên môi trường",
    BoTruongKhoaHocVaCongNghe: "Bộ trưởng Bộ Khoa học và Công nghệ",
    BoTruongNongNghiepVaPhatTrienNongThon:
        "Bộ trưởng Bộ Nông nghiệp và Phát triển nông thôn",
    BoTruongTaiChinh: "Bộ trưởng Bộ Tài chính",
    BoTruongTuPhap: "Bộ trưởng Bộ Tư pháp",
    ChanhAnToaAnNhaDanToiCao: "Chánh án tòa án nhân dân tối cao",
    ChinhPhu: "Chính phủ",
    ThuTuongChinhPhu: "Thủ tướng Chính phủ",
    ChuTichNuoc: "Chủ tịch nước",
    NganHangChinhSachXaHoi: "Ngân hàng chính sách xã hội",
    PhoThuTuongChinhPhu: "Phó Thủ tướng Chính phủ",
    QuocHoi: "Quốc hội",
    ThanhTraNhaNuoc: "Thanh tra Nhà nước",
};

export const REQUEST_STATUS_MAPPING: { [key: string]: string } = {
    pending: "Chờ tìm luật sư",
    starting: "Luật sư đang trả lời",
    done: "Luật sư đã trả lời",
    rejected: "Từ chối",
};

export const DEFAULT_IMAGES = [
    "https://picsum.photos/360/360",
    "https://picsum.photos/360/361",
    "https://picsum.photos/360/362",
    "https://picsum.photos/360/363",
    "https://picsum.photos/360/364",
];

export const errorMessageMapping: Record<string, string> = {
    "There is a booking at this time": "Đã có lịch đặt sân trong thời gian này",
    "Invalid booking time": "Thời gian đặt sân không hợp lệ",
    "The field is not working at this time.":
        "Sân không hoạt động vào thời gian này",
    "Phone number is invalid": "Số điện thoại không hợp lệ",
};
