name: Law assist frontend development CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:

  dev-container-build-push:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3.10.0
      id: buildx
      with:
        use: true

    # - name: Cache Docker image layers
    #   uses: actions/cache@v4.2.3
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-key: |
    #       ${{ runner.os }}-buildx-

    - name: Pre-build and push Dev container images
      uses: devcontainers/ci@v0.3.1900000328
      id: dev_container_prebuild
      with:
        platform: linux/amd64,linux/arm64
        imageName: ${{ secrets.DOCKER_USERNAME }}/frontend
        imageTag: dev-latest
        cacheFrom: ${{ secrets.DOCKER_USERNAME }}/frontend
        env: |
          NEXT_PUBLIC_API_HOST=${{ vars.NEXT_PUBLIC_API_HOST }}
          REMOTE_PROTOCOL=${{ vars.REMOTE_PROTOCOL }}
          REMOTE_HOSTNAME=${{ vars.REMOTE_HOSTNAME }}
          REMOTE_PHOTO_MOCK_DATA=${{ vars.REMOTE_PHOTO_MOCK_DATA }}
          NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET_DEV }}
          NODE_TLS_REJECT_UNAUTHORIZED=${{ secrets.NODE_TLS_REJECT_UNAUTHORIZED }}
        push: always
        runCmd: npm -v

    - name: Verify CI/CD pipeline
      run: echo ${{ steps.dev_container_prebuild.outputs.runCmdOutput }}
